Refactor/courses domain
iPhiTech-Applications/iPhiTech-Backend pull request #649
Opened 2023-06-22 11:07 UTC by iPhiSuhoon

## Description

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

2023-07-11 03:25 UTC, devmode2022 requested changes

2023-07-11 03:25 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    public function upload($file, $file_name)
Use the FileServices class upload method for this one

2023-07-11 03:47 UTC, devmode2022 requested changes

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Use the FileServices class upload method

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
No need for this one

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Have method in Services class for updates

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Have methods in Services class for creating record

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Can move to different Service since it have different model

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Have delete method in Services class

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseCategoryServices.php
> +        }
No need for this one if you can return null

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseCategoryServices.php
> +     * @return mixed|Collection|CourseCategory
Already returning mixed no need for Collection|CourseCategory

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseCategoryServices.php
> +     * @return bool
It can return CourseCategory object

2023-07-11 03:47 UTC, devmode2022 commented on app/Services/Courses/Services/CourseServices.php
> +    }
Different service

2023-07-11 03:47 UTC, devmode2022 commented on app/Applications/Courses/Controllers/CourseCategoryController.php
> +        $courseCategories = $this->courseCategoryService->browseCourseCategory(CourseCategoryBrowseDto::fromRequest($request));
You can use FilterDto instead of creating new one for filter

2023-07-11 03:47 UTC, devmode2022 commented on app/Applications/Courses/Controllers/CourseController.php
> +    }
This is redundant, already have the fileServices, and also you have the same method in the CourseServices class

2023-07-11 03:47 UTC, devmode2022 commented on app/Applications/Courses/Controllers/CourseController.php
> +        $user = auth('api')->user();
You can use this method in the services method to reduce the line in the controller and also reduce the parameters that needs to pass in the service method

2023-07-11 03:47 UTC, devmode2022 commented on app/Applications/Courses/Controllers/CourseController.php
> +        $file_path = $this->courseServices->uploadFile($request->file('featured_image'));
If you are using the uploadFile of courseServices here not sure what is the purpose of the upload method above ?

Again you can use the filterServices upload method, it is doing the same thing

2023-07-11 03:47 UTC, devmode2022 commented on app/Applications/Courses/Controllers/CourseController.php
> +        $course = CourseModel::find($id);
use the courseServices class instead of this one

2023-07-12 02:37 UTC, ri-bulatao approved these changes

2023-07-27 06:48 UTC, closed without merging